apiVersion: v1
kind: Endpoints # 类型为Endpoints
metadata:
  name: nginx-open # 与 service一致
  labels:
    app: nginx-open # 与 service一致
subsets:
  - addresses:
      - ip: <> # 目标ip
    ports:
      - name: web # 与 service一致
        port: 80
        protocol: TCP