apiVersion: v1 # api 文档版本 目前为v1
kind: Pod # 资源对象类型，例如：Pod、Deployment、StatefulSet 这一类对象等
metadata: # 用于描述资源对象的元数据
  name: nfs-demo # 名称
spec: # 资源规格 资源的各种规格，是期望达到这规格的一些规定
  containers: # 对应 容器的一些规定
    - name: nfs # 容器名称
      image: nginx # 容器所需要的镜像和版本（需要仓库里面有）

      volumeMounts: # 加载数据卷，避免数据丢失
        - name: balabala # 数据卷名称
          mountPath: /usr/share/nginx/html
  volumes:
    - name: balabala # 数据卷名称
      nfs:
        server: 192.168.198.161 # nfs ip
        path: /home/nfs/rw/wu/html # 网络存储路径
        readOnly: false # 可读写